export const hotelTypes = [
    { value: "hotel", label: "Hotel" },
    { value: "motel", label: "Motel" },
    { value: "resort", label: "Resort" },
    { value: "apartment", label: "Apartment" },
    { value: "hostel", label: "Hostel" },
    { value: "villa", label: "Villa" },
    { value: "inn", label: "Inn" },
    { value: "cottage", label: "Cottage" },
    { value: "lodge", label: "Lodge" },
    { value: "camp", label: "Camp" },
    { value: "boat", label: "Boat" },
    { value: "tent", label: "Tent" },
    { value: "treehouse", label: "Treehouse" },
    { value: "cabin", label: "Cabin" },
    { value: "chalet", label: "Chalet" },
    { value: "farmstay", label: "Farmstay" },
    { value: "townhouse", label: "Townhouse" },
    { value: "holiday home", label: "Holiday Home" },
    { value: "pension", label: "Pension" },
    { value: "ryokan", label: "Ryokan" },
    { value: "riyad", label: "Riyad" },
    { value: "heritage hotel", label: "Heritage Hotel" },
    { value: "boutique hotel", label: "Boutique Hotel" },
    { value: "apartment hotel", label: "Apartment Hotel" },
    { value: "guesthouse", label: "Guest House" },
]

export const hotelFacilities = [
    { value: "free parking", label: "Free Parking" },
    { value: "free wifi", label: "Free Wifi" },
    { value: "swimming pool", label: "Swimming Pool" },
    { value: "gym", label: "Gym" },
    { value: "restaurant", label: "Restaurant" },
    { value: "bar", label: "Bar" },
    { value: "24-hour front desk", label: "24-hour Front Desk" },
    { value: "garden", label: "Garden" },
    { value: "terrace", label: "Terrace" },
    {value:"fitness center", label: "Fitness Center" },
    {value:"spa", label: "Spa" },
    {value:"family rooms", label: "Family Rooms" },
    {value:"pets allowed", label: "Pets Allowed" },
    {value:"room service", label: "Room Service" },
    {value:"non-smoking rooms", label: "Non-Smoking Rooms" },


]